on:
  pull_request:
  merge_group:
  push:
    branches: [main]

env:
  RUSTFLAGS: -D warnings
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

name: ci
jobs:
  lint:
    name: code lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --all-features --benches --tests

      - name: cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --check

      - name: cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all --all-features --benches --tests

      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

